version: "2"
services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - 3306:3306
    env_file:
      - mysql.env

  wp:
    build: .
    container_name: wordpress
    restart: always
    ports:
      - 80:80
      - 443:443