- hosts: 'all'
  become: 'yes'
  gather_facts: no
  tasks:
  - name: Copy wp nginx edition
    copy: 
      src: ../files/docker/nginx/local_db/{{ item }}
      dest: /app/
    with_items:
      - docker-compose.yml
      - Dockerfile
      - start.sh
      - wp-conf
      - wp-config.php
      - mysql.env

  - name: Edit file wp-config.php
    lineinfile:
      dest: /app/wp-config.php
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    loop:
      - { regexp: "define\\( 'DB_NAME', '.*' \\);", line: "define( 'DB_NAME', 'wp' );" }
      - { regexp: "define\\( 'DB_USER', '.*' \\);", line: "define( 'DB_USER', 'wp_admin' );" }
      - { regexp: "define\\( 'DB_PASSWORD', '.*' \\);", line: "define( 'DB_PASSWORD', 'P@ssw0rd' );" }
      - { regexp: "define\\( 'DB_HOST', '.*' \\);", line: "define( 'DB_HOST', '{{ hostvars[inventory_hostname].ansible_host }}' );" }

  - name: Install python docker
    pip:
      name: 
        - docker
        - docker-compose
      extra_args: --user

  - name: Create and start services
    docker_compose:
      project_src: /app/
    register: output